### ISSUE TITLE
de.viadee.xai.anchor.adapter.tabular.builder does not exist

### ISSUE THREAD

**Issue by greenspray** [viadee/xai_examples#2]
First of all, thank you for painstakingly creating this detailed example. However, it seems like there is some issue with versioning in the achor library because maven's installation is not able to find the title mentioned class. 

I have made a reproducible example here -> https://github.com/greenspray/anchor_text_reprex

This is my java version
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

```
Some help would be greatly appreciated!

**Comment by TobiasGoerke** [comment]
Indeed, the artifacts on maven central are not up to date, causing the examples to have compile errors. I've just committed a patch making the xai_examples work again, as soon as maven central publishes the new artifacts; however, this might take a day or two. 

You can clone the javaAnchorAdapters (https://github.com/viadee/javaAnchorAdapters) and discretizer4j (https://github.com/viadee/discretizer4j) projects yourself and execute a mvn install on each. This will put all artifacts into your local repository and you won't have to wait for maven central.

I'm glad you are checking out anchorj. Just let me know if you encounter more issues.

**Comment by fkoehne** [comment]
Looking into it. We had some weird glitches with maven central deployments recently. :(

**Comment by greenspray** [comment]
Awesome! Thanks for the quick response guys. I will look into cloning so I can have the latest version of the code locally. Will update if there I encounter any other issues.

**Comment by fkoehne** [comment]
https://oss.sonatype.org/ just gave me a green light for the two build artifacts I released (although they are identical to those in the last deployments AFAIK).

The sync to maven central should happen in the next hours to days.
